/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Graph<String>test=new Graph<String>();
        Node<String> node1=test.addNode("Amman");
        Node<String> node2=test.addNode("Zarqa");
        Node<String> node3=test.addNode("Irbid");
        Node<String> node4=test.addNode("Aqabah");
        Node<String> node5=test.addNode("Karak");


        test.addEdge(node1,node2,true,10);
        test.addEdge(node1,node5,true,30);



//        test.addEdge(node1,node2,true);
      System.out.println(test.getNodes());
      System.out.println(test.graphList.containsKey(node1));
      System.out.println("N"+test.getNeighbors(node1));
      System.out.println(test.size());
//      for (Node key : test.graphList.keySet()) {
//        System.out.println(key);
//      }


    }
}
