/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int [] test={8,4,23,42,16,15};
        int [] test2=InsertionSort(test);

      for (int i : test2) {
        System.out.println(i);
      }


    }

    public static int [] InsertionSort(int[] arr){
      for (int i=1;i< arr.length;i++){
        int j=i-1;
        int temp=arr[i];
        while (j>=0 && temp<arr[j]){
          arr[j+1]=arr[j];
          j--;
        }
        arr[j + 1] =temp;

      }
      return arr;
    }
}
