/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// Resource https://www.youtube.com/watch?v=bBKu9gJr_y0
package HashTable;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        HashTable<String>HT=new HashTable<String>(20);
        HT.add(7,"RM");
        HT.add(20,"MAN U");
        HT.add(0,"PSG");
        HT.add(1,"ATM");
      System.out.println((1*7)%20);
      System.out.println("get ..."+HT.get(0));
//      try {
//        System.out.println(HT.get(90));
//      } catch (Exception e) {
//        e.printStackTrace();
//      }
      System.out.println(HT.contains(1));

    }
}
