/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static InsertionSort.App.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void testInsertionSort(){
      int [] test={8,4,23,42,16,15};
      int[]arr={4,8,15,16,23,42};
      assertEquals(arr,InsertionSort(test));
    }
}
